version: 2
updates:

  # oclif CLI
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    groups:
      production-dependencies:
        dependency-type: production
      development-dependencies:
        dependency-type: development
    versioning-strategy: increase

  # Actions used in GitHub Workflows
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
