name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

  workflow_dispatch:  # Allows the workflow to be triggered manually

env:
  JOB_NODE_VERSION: '20.19.4'  # Chosen to match what is used internally by the Heroku CLI

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.JOB_NODE_VERSION }}
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Run eslint
        run: yarn lint

  unit-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.JOB_NODE_VERSION }}
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Run unit tests
        run: yarn test
